### ISSUE TITLE
Linker/compilation errors on Debian/Ubuntu with wxWidgets distro package (v3.0.4)

### ISSUE THREAD

**Issue by solemnwarning** [pkulchenko/wxlua#80] opened 2020-12-12 23:26 UTC
I can't get wxLua 3.1.0.0 or the current master branch to build under Debian against wxWidgets 3.0.4, I've tried both the GTK2 and GTK3 versions of wxWidgets (from Debian) and 3.1.0.0 fails against both with the following error:

```
[ 95%] Linking CXX executable ../../bin/Debug/wxLua
[ 95%] Linking CXX executable ../../bin/Debug/wxLuaFreeze
[ 96%] Linking CXX executable ../../bin/Debug/wxLuaCan
/usr/bin/ld: ../../lib/Debug/libwxlua_bind-wx30d-3.1.0.0.so: undefined reference to `wxPluralFormsCalculatorPtr::~wxPluralFormsCalculatorPtr()'
collect2: error: ld returned 1 exit status
make[2]: *** [apps/wxluafreeze/CMakeFiles/wxLuaFreeze.dir/build.make:89: bin/Debug/wxLuaFreeze] Error 1
make[1]: *** [CMakeFiles/Makefile2:715: apps/wxluafreeze/CMakeFiles/wxLuaFreeze.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: ../../lib/Debug/libwxlua_bind-wx30d-3.1.0.0.so: undefined reference to `wxPluralFormsCalculatorPtr::~wxPluralFormsCalculatorPtr()'
collect2: error: ld returned 1 exit status
make[2]: *** [apps/wxlua/CMakeFiles/wxLua_app.dir/build.make:89: bin/Debug/wxLua] Error 1
make[1]: *** [CMakeFiles/Makefile2:597: apps/wxlua/CMakeFiles/wxLua_app.dir/all] Error 2
/usr/bin/ld: ../../lib/Debug/libwxlua_bind-wx30d-3.1.0.0.so: undefined reference to `wxPluralFormsCalculatorPtr::~wxPluralFormsCalculatorPtr()'
collect2: error: ld returned 1 exit status
make[2]: *** [apps/wxluacan/CMakeFiles/wxLuaCan.dir/build.make:134: bin/Debug/wxLuaCan] Error 1
make[1]: *** [CMakeFiles/Makefile2:656: apps/wxluacan/CMakeFiles/wxLuaCan.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

master branch fails earlier with a some compilation errors:

```
/home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_bind.cpp: In function ‘wxLuaBindNumber* wxLuaGetDefineList_wxcore(size_t&)’:
/home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_bind.cpp:1345:29: error: ‘wxFILTER_SPACE’ was not declared in this scope
         { "wxFILTER_SPACE", wxFILTER_SPACE },
                             ^~~~~~~~~~~~~~
/home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_bind.cpp:1345:29: note: suggested alternative: ‘wxFILTER_NONE’
         { "wxFILTER_SPACE", wxFILTER_SPACE },
                             ^~~~~~~~~~~~~~
                             wxFILTER_NONE
/home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_bind.cpp:1346:31: error: ‘wxFILTER_XDIGITS’ was not declared in this scope
         { "wxFILTER_XDIGITS", wxFILTER_XDIGITS },
                               ^~~~~~~~~~~~~~~~
/home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_bind.cpp:1346:31: note: suggested alternative: ‘wxFILTER_DIGITS’
         { "wxFILTER_XDIGITS", wxFILTER_XDIGITS },
                               ^~~~~~~~~~~~~~~~
                               wxFILTER_DIGITS
/home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_bind.cpp:1427:37: error: ‘wxFONTWEIGHT_EXTRABOLD’ was not declared in this scope
         { "wxFONTWEIGHT_EXTRABOLD", wxFONTWEIGHT_EXTRABOLD },
                                     ^~~~~~~~~~~~~~~~~~~~~~
/home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_bind.cpp:1427:37: note: suggested alternative: ‘wxFONTWEIGHT_BOLD’
         { "wxFONTWEIGHT_EXTRABOLD", wxFONTWEIGHT_EXTRABOLD },
                                     ^~~~~~~~~~~~~~~~~~~~~~
                                     wxFONTWEIGHT_BOLD
/home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_bind.cpp:1432:38: error: ‘wxFONTWEIGHT_EXTRAHEAVY’ was not declared in this scope
         { "wxFONTWEIGHT_EXTRAHEAVY", wxFONTWEIGHT_EXTRAHEAVY },
                                      ^~~~~~~~~~~~~~~~~~~~~~~
/home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_bind.cpp:1432:38: note: suggested alternative: ‘wxFONTWEIGHT_NORMAL’
         { "wxFONTWEIGHT_EXTRAHEAVY", wxFONTWEIGHT_EXTRAHEAVY },
                                      ^~~~~~~~~~~~~~~~~~~~~~~
                                      wxFONTWEIGHT_NORMAL
/home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_bind.cpp:1441:33: error: ‘wxFONTWEIGHT_HEAVY’ was not declared in this scope
         { "wxFONTWEIGHT_HEAVY", wxFONTWEIGHT_HEAVY },
                                 ^~~~~~~~~~~~~~~~~~
/home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_bind.cpp:1441:33: note: suggested alternative: ‘wxFONTWEIGHT_MAX’
         { "wxFONTWEIGHT_HEAVY", wxFONTWEIGHT_HEAVY },
                                 ^~~~~~~~~~~~~~~~~~
                                 wxFONTWEIGHT_MAX
```

```
/home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_controls.cpp: In function ‘int wxLua_wxHeaderCtrl_GetColumnTitleWidth(lua_State*)’:
/home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_controls.cpp:766:49: error: no matching function for call to ‘wxHeaderCtrl::GetColumnTitleWidth(unsigned int&)’
     int returns = (self->GetColumnTitleWidth(idx));
                                                 ^
In file included from /home/solemnwarning/src/wxlua/wxLua/modules/wxbind/include/wxcore_bind.h:121,
                 from /home/solemnwarning/src/wxlua/wxLua/modules/wxbind/src/wxcore_controls.cpp:19:
/usr/include/wx-3.0/wx/headerctrl.h:157:9: note: candidate: ‘int wxHeaderCtrlBase::GetColumnTitleWidth(const wxHeaderColumn&)’
     int GetColumnTitleWidth(const wxHeaderColumn& col);
         ^~~~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/headerctrl.h:157:9: note:   no known conversion for argument 1 from ‘unsigned int’ to ‘const wxHeaderColumn&’
```

**Comment by pkulchenko** [comment] 2020-12-13 06:45
@solemnwarning, thank you for the report. Several recent updates didn't set the version when the changes were introduces, which affected the compilation for wxwidgets prior 3.1.2. I'm pushing several commits that should fix this. Let me know if you still run into any errors.

**Comment by solemnwarning** [comment] 2020-12-13 10:02
That was fast! Compilation issues on master are fixed now, but it fails to link with the same error as 3.1.0.0.

**Comment by solemnwarning** [comment] 2020-12-13 10:23
FYI `wxLua_wxMsgCatalog_delete_function()` in `wxLua/modules/wxbind/src/wxbase_base.cpp` is the source of the call to `wxPluralFormsCalculatorPtr::~wxPluralFormsCalculatorPtr()` - commenting out the delete line is enough to at least make it link.

**Comment by solemnwarning** [comment] 2020-12-13 11:37
The same build issue is present on Ubuntu too... looks like a wxWidgets/package bug. 3.0.0.9 builds since it doesn't have the translation stuff.

**Comment by pkulchenko** [comment] 2020-12-13 17:41
Interesting. I don't get this error (as I tested the compilation for 3.1.0.0 on all supported platforms).

I see `wxPluralFormsCalculator` as a private class in wxwidgets, but I'm not sure why the reference to `wxPluralFormsCalculatorPtr` would be undefined if it's declared in translation.h:

```
class wxPluralFormsCalculator;
wxDECLARE_SCOPED_PTR(wxPluralFormsCalculator, wxPluralFormsCalculatorPtr)
```

I'm not yet sure what's happening with this declaration or why I can't reproduce this locally.

**Comment by pkulchenko** [comment] 2020-12-13 17:50
@solemnwarning, see a related discussion in #78. Are you building with `--with-gtk=3` by any chance? That's the configuration I used when I built and tested on Ubuntu.

**Comment by solemnwarning** [comment] 2020-12-13 18:14
I'm using the distro wxWidgets packages. GTK2 vs. GTK3 (Debian has both available) doesn't seem to make a difference.

**Comment by pkulchenko** [comment] 2020-12-13 18:28
Then I tend to agree with you; this looks like a wxWidgets/package bug, like you said. I don't get this error when building wxwidgets from scratch.

You may also try setting `wxUSE_INTL` to 0 to exclude wxTranslations related methods from wxlua.

**Comment by solemnwarning** [comment] 2020-12-14 00:15
I've tried setting `-DwxUSE_INTL=0` in `wxWidgets_CXX_FLAGS` and `CMAKE_CXX_FLAGS`, no change.

**Comment by pkulchenko** [comment] 2020-12-14 00:54
@solemnwarning, I think this should be a flag for wxwidgets compilation, but since it's already compiled, wxlua just picks available options from wxwidgets config.

I think I'll add `wxLUA_USE_wxTranslations` option or something along those lines, which will allow you to exclude all `wxTranslations` related classes when building wxlua.

**Comment by pkulchenko** [comment] 2020-12-14 01:40
@solemnwarning, I added `wxLUA_USE_wxTranslations` that you can set to 0 in wxlua cmake call (by adding `-DwxLUA_USE_wxTranslations=0` as I understand), which should exclude wxTranslations from your wxlua configuration. Let me know if this eliminates the errors.

**Comment by solemnwarning** [comment] 2020-12-14 18:26
Setting `wxLUA_USE_wxTranslations` to 0 in `wxluasetup.h` works, setting it via CMake doesn't help as it gets overwritten by the `wxluasetup.h` macro.

As a side note, I've been prototyping adding Lua plugin support to one of my projects using wxLua. I was hoping to use the binding generation to add bindings for my own APIs, but `genwxbind.lua` doesn't seem to support templates, which my application makes heavy use of (both STL containers and my own templates).

What are your thoughts on this - is there a clean way to add bindings for templates via `genwxbind.lua`, or am I going to have to come up with some Frankenstein combination of wxLua's bindings and another Lua wrapper that can handle the templated things?

Thanks

**Comment by pkulchenko** [comment] 2020-12-14 19:06
> Setting wxLUA_USE_wxTranslations to 0 in wxluasetup.h works, setting it via CMake doesn't help as it gets overwritten by the wxluasetup.h macro.

Are you familiar enough with what happens in CMake setup to see how this can be addressed? Ideally wxluasetup.h should provide the defaults that can still be overwritten from the command line. Should we replace `#define` with something like `#ifndef ... #define...` to make it work?

> What are your thoughts on this - is there a clean way to add bindings for templates via genwxbind.lua, or am I going to have to come up with some Frankenstein combination of wxLua's bindings and another Lua wrapper that can handle the templated things?

If you have some examples, we can probably tweak genwxbind.lua to handle that, but I can warn you that it's not a straightforward exercise, as the script is quite complex and I only understand a small part of what happens there. Feel free to open a separate ticket for this to explore.

**Comment by pkulchenko** [comment] 2020-12-15 01:30
@solemnwarning, I pushed a couple of updates that should exlcude wxTranslations if you set `-DCMAKE_CXX_FLAGS="-DwxLUA_USE_wxTranslations=0"` in CMake parameters. Let me know if this eliminates the compilation errors.

**Comment by solemnwarning** [comment] 2020-12-16 09:28
That works - can build on Debian without patching anything now.

**Comment by pkulchenko** [comment] 2020-12-16 18:20
@solemnwarning, merged the changes; thank you for checking!

**Comment by Mailaender** [comment] 2022-05-21 12:31
Can you tag a new release that incorporates these fixes?

**Comment by pkulchenko** [comment] 2022-05-21 18:51
Yes, plan to do this shortly. Working on a couple of updates to make it compile against the current wxwidgets master.

**Comment by pkulchenko** [comment] 2022-10-28 05:00
@Mailaender, v3.2.0.0 has been tagged and released.

**Comment by Mailaender** [comment] 2022-10-29 15:49
> ld: lib/Debug/libwxlua_bind-wx31gtk3ud-3.2.0.0.so: undefined reference to `wxRichTextStyleComboPopup::OnMouseMove(wxMouseEvent&)'

> ld: lib/Debug/libwxlua_bind-wx31gtk3ud-3.2.0.0.so: undefined reference to `wxRichTextStyleComboPopup::OnMouseClick(wxMouseEvent&)'

**Comment by pkulchenko** [comment] 2022-10-29 15:57
@Mailaender, thank you for the report; what's the cmake command for wxlua?

**Comment by pkulchenko** [comment] 2022-10-29 16:08
There is definitely `wxRichTextStyleComboPopup::OnMouseClick` that was introduced [long time ago](https://github.com/wxWidgets/wxWidgets/commit/e637208a3210dfae3ee044cc5b7179fd76082769#diff-6d3ab6714afd83d018a40c43e83915f5d24500df652955137f89cad576964e94R306), but for some reason I don't see it in the interface files. Is it not exported by the wxwidgets so?

**Comment by pkulchenko** [comment] 2022-10-29 16:11
> ld: lib/Debug/libwxlua_bind-wx31gtk3ud-3.2.0.0.so: undefined reference to `wxRichTextStyleComboPopup::OnMouseClick(wxMouseEvent&)'

@toshinagata, any ideas on this error? I didn't get any errors on Windows, but for some reason it doesn't seem to be present on Linux.

**Comment by toshinagata** [comment] 2022-10-30 01:29
@pkulchenko, I'm sorry I have no idea about the error, but I do have one concern about richtextstyles.h. The declaration of wxRichTextStyleComboPopup does not have "WXDLLIMPEXP_RICHTEXT" label. I also noticed that the class wxRichTextStyleComboPopup is not listed in the wxWidgets documentation. Does it mean this class is only for internal use, and should not be used by ordinary users? If that is the case, we should consider removing the implementation of this class from wxlua.

**Comment by pkulchenko** [comment] 2022-10-30 03:50
I agree; I can remove it, although I don't see anything wrong with its implementation, but can understand why it may not be included in compiled libraries.

**Comment by pkulchenko** [comment] 2022-10-30 04:58
@Mailaender, could you try with the current master? If the build works, I'll cut a new release. Thanks!

**Closed** 2022-10-30 04:57 UTC

**Comment by Mailaender** [comment] 2022-10-30 08:58
I can confirm that https://github.com/pkulchenko/wxlua/commit/80f0bd99c4dc71d8fb2fe573ad1f8b954581e8a3 successfully compiles against wxWidgets 3.1.4 (chose that because zbstudio is compiled with it)

**Comment by pkulchenko** [comment] 2022-10-30 15:05
Thanks. Tagged with 3.2.0.1 and pushed.
