### ISSUE TITLE
undefined symbol: lua_tonumber

### ISSUE THREAD

**Issue by hollunder** [pkulchenko/wxlua#47] opened 2019-11-19 16:20 UTC
Hi Paul,
I have just tried to build zbstudio using this and it failed during the CMake step due to not finding the wx module. I have tried to replicate what the script does and that fails as well.
It is quite possible I do something wrong somewhere. I'm currently trying to adapt the zerobrane-studio packagebuild for testing with wxlua-git and the all-binaries-190c branch.
I saw that the original PKGBUILD I'm adapting removes the check for the wx module, so there probably has been something wrong for a while now. For reference, this is what I take as base and modify: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zerobrane-studio

```lua
$ lua5.3 -e 'require("wx")'
lua5.3: error loading module 'wx' from file '/usr/lib/lua/5.3/wx.so':
	/usr/lib/lua/5.3/wx.so: undefined symbol: lua_tonumber
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: in ?
```

**Comment by pkulchenko** [comment] 2019-11-19 16:40
@hollunder, I'm not sure what exactly is happening, but I don't think it's the problem with wxlua. `lua_tonumber` is a macro, so it doesn't exist as a function. It looks like a case of mismatched Lua versions or incorrect setup.

Can you provide the output of `ldd -v -d -r /usr/lib/lua/5.3/wx.so`? Where did `wx.so` in that folder come from? Are you trying to build wxlua for Lua 5.3 or are you trying to build and run zbstudio? If the latter, then it's better to use Lua 5.1 for it, even though I did include improvements in both wxlua and ZeroBrane Studio to be launched with Lua 5.2 and Lua 5.3 (https://www.freelists.org/post/zerobrane/New-beta-version-of-ZeroBrane-Studio-is-available,9)

**Comment by hollunder** [comment] 2019-11-21 07:49
```
$ pacman -Qo /usr/lib/lua/5.3/wx.so
/usr/lib/lua/5.3/wx.so is owned by wxlua-git 3.0.0.6.r3.g7afa3a7-1
```

[ldd.txt](https://github.com/pkulchenko/wxlua/files/3873406/ldd.txt)

I am indeed trying to build and run wxlua and zbstudio with Lua 5.3 on Arch Linux.

**Comment by pkulchenko** [comment] 2019-11-21 22:53
This looks like the case of wxlua compilation against 5.1 headers when only 5.3 so library is present (this is why those functions are marked as absent in the ldd output). I'm not sure what your `cmake` command looks like, but you can set `-DwxLua_LUA_INCLUDE_DIR` and `-DwxLua_LUA_LIBRARY` to point to the header files and `liblua.a` locations.

Having said that, I'm not sure why you are trying to build wxlua yourself if the one packaged with ZeroBrane Studio should work just fine. Try installing this package: https://download.zerobrane.com/ZeroBraneStudioEduPack-1.80-linux.sh.

**Comment by hollunder** [comment] 2019-11-22 12:21
Oh your distributed package works (without install and probably with as well), but this is more about installing the program in the common way, using shared libraries and through the package manager.

I got it to work, but I don't fully understand the situation.

1) ldd still can't find the symbols.
[ldd.txt](https://github.com/pkulchenko/wxlua/files/3879392/ldd.txt)

2) But the little test works fine now
```
$ lua5.3 -e 'require("wx")'
```

3) zbstudio from `all-binaries-190c` no longer errors either and launches after I fix the launch script.
The script installed as `/usr/bin/zbstudio` tries to call Lua using `bin/linux/$ARCH/lua` which does not work on my distro and I doubt that it works on others. If I replace that bit with `/usr/bin/lua` or just `lua` and let PATH sort it out then zbstudio starts fine.

These are my wxlua and zbstudio PKGBUILD scripts for reference. They are not perfect, but maybe it helps in some way. Github is silly and doesn't like files without extension, so I append the program name and `.txt.` Remove that if you want to run it on Arch.

[PKGBUILD-wxlua.txt](https://github.com/pkulchenko/wxlua/files/3879443/PKGBUILD-wxlua.txt)
[PKGBUILD-zbs-190c.txt](https://github.com/pkulchenko/wxlua/files/3879447/PKGBUILD-zbs-190c.txt)

Thanks for your help Paul.

**Comment by pkulchenko** [comment] 2019-11-22 17:39
Thank you for the update!

> zbstudio from all-binaries-190c no longer errors either and launches after I fix the launch script.

I think it's because I fixed some of the issues that prevented ZBS to be launched using Lua 5.2 or Lua 5.3 interpreter.

> The script installed as /usr/bin/zbstudio tries to call Lua using bin/linux/$ARCH/lua which does not work on my distro and I doubt that it works on others.

It's because `bin/linux/$ARCH/lua` launched Lua 5.1, but your wxlua library is for Lua 5.3. Try changing `bin/linux/$ARCH/lua` call to `bin/linux/$ARCH/lua53` in `/usr/bin/zbstudio` and it may work.

> PKGBUILD-zbs-190c.txt

This should work, but don't reference this branch in the scripts, as it's just a temporary one for testing. I expect all these changes to be included in the master branch and released as v1.90. I presume these are just scripts for your local testing, but still wanted to mention this.

I'm closing this ticket, as it looks to be working with the current version of wxlua.

**Closed by pkulchenko** 2019-11-22 17:39 UTC

**Comment by hollunder** [comment] 2019-11-23 23:09
> Thank you for the update!
> 
> > zbstudio from all-binaries-190c no longer errors either and launches after I fix the launch script.
> 
> I think it's because I fixed some of the issues that prevented ZBS to be launched using Lua 5.2 or Lua 5.3 interpreter.

If it was related to the lua_tonumber test then that may well be the case.

> > The script installed as /usr/bin/zbstudio tries to call Lua using bin/linux/$ARCH/lua which does not work on my distro and I doubt that it works on others.
> 
> It's because `bin/linux/$ARCH/lua` launched Lua 5.1, but your wxlua library is for Lua 5.3. Try changing `bin/linux/$ARCH/lua` call to `bin/linux/$ARCH/lua53` in `/usr/bin/zbstudio` and it may work.

Definitely does not work for me. Also 5.3 is the default on my distro, so:
```
$ lua -v
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
```
Why I think it doesn't work. For one, if it is supposed to call a shipped Lua binary, there is no `bin` in the current directory.
```
$ ls "/usr/share/zbstudio" 
api  cfg  interpreters  lualibs  packages  spec  src  zbstudio
```
If it was supposed to be for a system wide Lua installation then it's missing a leading `/` to make it an absolute path and the path also wouldn't exist. Not on my system at least, but in that regard distros vary. On my system the Lua binaries can be found under `/usr/bin`:
```
$ ls -l /usr/bin/lua*
-rwxr-xr-x 1 root root 243584 Jän 10  2019 /usr/bin/lua
-rwxr-xr-x 1 root root 186240 Jän 11  2019 /usr/bin/lua5.1
-rwxr-xr-x 1 root root 210816 Jän 10  2019 /usr/bin/lua5.2
lrwxrwxrwx 1 root root     12 Jän 10  2019 /usr/bin/lua5.3 -> /usr/bin/lua
-rwxr-xr-x 1 root root 157592 Jän 10  2019 /usr/bin/luac
-rwxr-xr-x 1 root root 128920 Jän 11  2019 /usr/bin/luac5.1
-rwxr-xr-x 1 root root 141208 Jän 10  2019 /usr/bin/luac5.2
lrwxrwxrwx 1 root root     13 Jän 10  2019 /usr/bin/luac5.3 -> /usr/bin/luac
-rwxr-xr-x 1 root root     43 Apr 16  2019 /usr/bin/luacheck
lrwxrwxrwx 1 root root     12 Nov  9  2018 /usr/bin/luajit -> luajit-2.0.5
-rwxr-xr-x 1 root root 468928 Nov  9  2018 /usr/bin/luajit-2.0.5
-rwxr-xr-x 1 root root   1437 Sep 11 16:50 /usr/bin/luarocks
-rwxr-xr-x 1 root root    919 Sep 11 16:50 /usr/bin/luarocks-admin
```
I don't know for certain how it is handled on e.g. Debian based systems, it tends to be a bit different.

> > PKGBUILD-zbs-190c.txt
> 
> This should work, but don't reference this branch in the scripts, as it's just a temporary one for testing. I expect all these changes to be included in the master branch and released as v1.90. I presume these are just scripts for your local testing, but still wanted to mention this.

I'd not use an experimental/release branch if I were to distribute it, which I don't feel comfortable doing at the moment anyway.

> I'm closing this ticket, as it looks to be working with the current version of wxlua.

Yep, thanks for the help.

**Comment by hollunder** [comment] 2019-11-26 17:55
Now I've come around to actually using zbstudio and it has issues with this version of zbstudio. I tried to create a file but got an error. Same with renaming said file.
![2019-11-26-185304_1366x768_scrot](https://user-images.githubusercontent.com/8207622/69659210-012ef600-107e-11ea-8a87-7123eb9f6c58.png)
My guess is that this comes from the undefined symbols.
Apparently they were found during compilation, but not at runtime?
[ldd.txt](https://github.com/pkulchenko/wxlua/files/3893300/ldd.txt)

**Comment by pkulchenko** [comment] 2019-11-26 18:01
I don't think it's caused by undefined symbols. I did have a recent patch for this in the upgrade branch (as Lua 5.3 is more strict about values provided to `tonumber` call): https://github.com/pkulchenko/ZeroBraneStudio/commit/3dd1c3bfbfe9b84227bafcf75eb3f08c5cb7a0d6.

You can apply the changes from the commit, which should eliminate this issue.

**Comment by hollunder** [comment] 2019-11-26 20:12
Thanks Paul, that appears to have done the trick.
I patched the file manually and I think you might have missed a tonumber in `src/util.lua` in your patch as I had three occurrences of `tonumber(755,8)`.

**Comment by pkulchenko** [comment] 2019-11-26 20:50
Yes, that one was patched in an earlier commit. Thank you for the update.
